# Local Development
[profile.default]
address = "localhost:7233"
namespace = "default"


# Used for Testing Docker Compose
[profile.preview]
address = "temporal:7233"
namespace = "default"

# Use for Production
[profile.production]
address = "serverless-gcp.sdvdw.tmprl.cloud:7233"
namespace = "serverless-gcp.sdvdw"